image: jacknoordhuis/pocketmine-hybrid

stages:
 - package

before_script:
 - git submodule update --init --recursive
 - ./applypatches.sh

phar:
  stage: package
  script:
   - sed -i "s/const VERSION \?= \?\"\(.*\)\"/const VERSION = \"\1$([ ${CI_BUILD_REF_NAME} != master ] && echo unsupported-)${CI_BUILD_REF:0:7}\"/" PocketMine-Hybrid-Core/src/pocketmine/PocketMine.php
   - sed -i "/GIT_COMMIT/s/0000000000000000000000000000000000000000/${CI_BUILD_REF}/" PocketMine-Hybrid-Core/src/pocketmine/PocketMine.php
   - ./tests/travis.sh
   - mv PocketMine-Hybrid-Core/plugins/DevTools/PocketMine-Hybrid*.phar .
  artifacts:
    paths:
     - PocketMine-Hybrid*.phar