---
image: jacknoordhuis/pocketmine-hybrid

stages:
 - package

before_script:
 - git config --global user.email "$GIT_USER_EMAIL"
 - git config --global user.name "$GIT_USER_NAME"
 - git submodule update --init --recursive
 - cp -r /pocketmine/* ./
 - ./applyPatches.sh
 - cp -r PocketMine-Hybrid-Core/* ./
 - ./runPreProcessor.sh -d $CI_PROJECT_DIR/src/pocketmine
 - rm -rf PocketMine-MP PocketMine-Hybrid-Core PocketMine-MP-Patches resources doxygen.conf start.ps1 start.cmd applyPatches.sh rebuildPatches.sh upstreamMerge.sh runPreProcessor.sh
 - bin/php7/bin/php bin/composer.phar install


phar:
  stage: package
  script:
   - ./tests/travis.sh -p $CI_PROJECT_DIR/bin/php7/bin/php
   - mv PocketMine-MP.phar PocketMine-Hybrid.phar
  artifacts:
    paths:
     - PocketMine-Hybrid.phar
...