---
version: 2
jobs:
  working_directory: /pocketmine
  build:
    docker:
      # specify the version you desire here
      - image: jacknoordhuis/pocketmine-hybrid:0.0.1
    steps:
      - checkout:
          build_dir: /pocketmine
      - run: ./applypatches.sh
      - run: cp PocketMine-Hybrid-Core/* ./../
      - run: cd ..
      - run: composer install
      - run: ./tests/travis.sh
      - store_artifacts:
          path: /plugins/DevTools/PocketMine-Hybrid*.phar
          destination: PocketMine-Hybrid.phar
...